version: '3.1'
services:
  mongo:
      image: mongo
      restart: always
      environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: example


  web-analyzer:
      build: .
      restart: always
      ports:
        - 4444:80
      environment:
        MongoDB__Host: mongo
      depends_on:
        - mongo
      links:
        - mongo
