name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build/Run the tests
      run: docker-compose up -d
      working-directory: ./selenium-tests
    - name: Check running containers
      run: docker ps
    - name: Wait for test to run
      uses: jakejarvis/wait-action@v0.1.0
      with:
        time: '30s'
    - name: Test logs
      run: docker-compose logs sut
    - name: Check the test result
      run: docker-compose logs sut | grep 'OK'
      working-directory: ./selenium-tests
    - name: Break down the docker containers
      run: docker-compose down
      working-directory: ./selenium-tests            
